### ISSUE TITLE
Cabal test issue

### ISSUE THREAD

**Issue by prolic** [futrnostr/futr#25]
```bash
cabal run futr-tests
...
All 97 tests passed (0.06s)
```

however:

```bash
cabal test
...
Error: [Cabal-9341]
Failed to find the installed unit 'futr-0.1.0.0-inplace' in package database stack.

Error: [Cabal-7125]
Tests failed for futr-0.1.0.0.
```

**Comment by prolic** [comment]
@ProofOfKeags May I ask you to give me a hint? I don't know why this happens and seem to be unable to fix it.

**Comment by ProofOfKeags** [comment]
I don't use cabal. I'm still on stack. I don't get to use Haskell daily anymore sadly. It looks like the package is not in the cache though fwiw.

**Comment by prolic** [comment]
@ProofOfKeags Thanks, I'll keep trying.

**Comment by maridonkers** [comment]
This seems to be the same problem: [cabal test all](https://github.com/haskell/cabal/issues/10046)

**Comment by prolic** [comment]
@maridonkers Thanks mate! It drove me really crazy and I already declared myself incompetent, haha.

Can confirm, downgrading to cabal 3.10.3.0 resolved the issue.
