### ISSUE TITLE
failed to install GHCUp

### ISSUE THREAD

**Issue by starius** [futrnostr/futr#31]
I'm running `curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh` on Debian 12.
Got the following error:
```
[ Info  ] verifying digest of: ghc-9.4.8-x86_64-deb11-linux.tar.xz
[ Info  ] Unpacking: ghc-9.4.8-x86_64-deb11-linux.tar.xz to /home/user/.ghcup/tmp/ghcup-30f8eb907a0e084e
[ Info  ] Installing GHC (this may take a while)






[ Error ] [GHCup-00841] Process "sh" with arguments ["./configure",
[ ...   ]                              "--prefix=/home/user/.ghcup/ghc/9.4.8"] failed with exit code 77.
[ Error ] Also check the logs in /home/user/.ghcup/logs
"ghcup --metadata-fetching-mode=Strict --cache install ghc recommended" failed!
```

I checked the logs:

```
$ cat /home/user/.ghcup/logs/ghcup.log 
Debug: Identified Platform as: Linux Debian, 12
Debug: last access was 17.138804605s ago, cache interval is 300s
Debug: Decoding yaml at: /home/user/.ghcup/cache/ghcup-0.0.8.yaml
Debug: Requested to install GHC with 9.4.8
Info: verifying digest of: ghc-9.4.8-x86_64-deb11-linux.tar.xz
Info: Unpacking: ghc-9.4.8-x86_64-deb11-linux.tar.xz to /home/user/.ghcup/tmp/ghcup-30f8eb907a0e084e
Info: Installing GHC (this may take a while)
Debug: Running sh with arguments ["./configure","--prefix=/home/user/.ghcup/ghc/9.4.8"]
Error: [GHCup-00841] Process "sh" with arguments ["./configure",
                             "--prefix=/home/user/.ghcup/ghc/9.4.8"] failed with exit code 77.
Error: Also check the logs in /home/user/.ghcup/logs
```

File `/home/user/.ghcup/logs/ghc-configure.log` is empty.

**Comment by prolic** [comment]
I'm sorry, but I don't maintain ghcup.

**Comment by prolic** [comment]
Did you install build essentials?

**Comment by starius** [comment]
> Did you install build essentials? On Fri, Oct 11, 2024, 21:24 Sascha-Oliver Prolic < ***@***.***> wrote:

Yes

**Comment by prolic** [comment]
Alright, I'll try to grab some debian docker image to reproduce. In the
meantime, try Google.

**Comment by starius** [comment]
Here https://www.haskell.org/ghcup/install/#version-12 I found this command:

```
$ sudo apt-get install build-essential curl libffi-dev libffi8 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5
```

in my case `libncurses5 libtinfo5` were missing.

But it didn't help.

**Comment by prolic** [comment]
Try installing those first

build-essential curl libffi-dev libffi8 libgmp-dev libgmp10 libncurses-dev
libncurses5 libtinfo5

**Comment by starius** [comment]
Hmm, I found that `~/.ghcup/bin/ghcup` exists.
I ran `ghcup install ghc 9.6.6` and got a meaningful message:
```
$ ghcup install ghc 9.6.6
...
[ Info  ] Installing GHC (this may take a while)
ghcup: /home/user/.ghcup/tmp/ghcup-50bec6882704369d: createDirectory: resource exhausted (No space left on device)
```

I'll try with larger disk space. Probably this was the root cause. So the problem was that this error message was not shown when running `curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh`

**Comment by prolic** [comment]
Glad you found out. Let me know how it goes

**Comment by starius** [comment]
It works on a machine with enough free space!
